#!/bin/sh

# That extremely bright individual who has desided that linking all of these 'submodules' to a specific commit rather than the repo itself is appropriate must be hanged

MODULES="hotchlib"

for MODULE in $MODULES; do
	echo ">>>> $MODULE"
	
	cd $MODULE
	git checkout master
	git fetch
	cd ..
done
